### PR TITLE
Change GetLogFilters to get *all* entries, not just the first 10

### PR DESCRIPTION
**Pull request by tgjonestx**
More fixes for https://jira.zenoss.com/browse/CC-3673

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by tgjonestx** [comment]
retest this

**Pull request merged**
