### PR TITLE
Rewrite all the integration tests to be quick

### PR DESCRIPTION
**Pull request by iancmcc**
Please do not merge this. It is being used to test the Jenkins integration.

### CODE REVIEW

**Comment by iancmcc** [comment]
retest this

**Comment by iancmcc** [comment]
retest this

**Comment by iancmcc** [comment]
retest this

**Comment by iancmcc** [comment]
retest this

**Comment by iancmcc** [comment]
retest this, please

**Comment by iancmcc** [comment]
retest this

**Comment by tgjonestx** [comment]
retest this

**Pull request closed without merging**
