### PR TITLE
ZEN-22546 Add uintToInt cast function

### PR DESCRIPTION
**Pull request by carlcamera**
add cast function for use in GO templates

### CODE REVIEW

**Comment by jpeacock-zenoss** [comment]
I suppose the user of `unitToInt` just needs to be careful about using `uint` values bigger than `int`.

**Comment by iancmcc** [comment]
This isn't the only place those functions are defined for templates. There are a couple others you should look for.

**Comment by carlcamera** [comment]
So @iancmcc are you saying
1. This change is unacceptable until those other locations are found and also updated or
2. Know Thee Well that other template function files exist and Carry On.

I need this function for the MariaDB-model template change and it works, so not sure how to proceed in light of your comment above.

**Comment by iancmcc** [comment]
The former. Unless it's unsuited to the other template evaluators.

**Comment by iancmcc** [comment]
The other template evaluators got consolidated, so no other changes are necessary.

**Comment by carlcamera** [comment]
Update: Ian checked and someone has consolidated the GO functions into just the one evaluate.go file so only one file needs updating after all.

**Pull request merged**
