### PR TITLE
CC-4318 Add serviced config param that enables centralized isvcs logstash output

### PR DESCRIPTION
**Pull request by ealii**

### CODE REVIEW

**Comment by jbirdkerr** [comment]
The code looks sound, but I'm currently figuring out how best to test the new binary. I'm currently trying to start a build of http://platform-jenkins.zenoss.eng/job/ControlCenter/job/develop/job/merge-start/ so that we can install the new `deb` on a throwaway CZ, but having trouble with access.

If you have screenshots proving out the functionality, please add them. If not, I'll need to get the unstable build of `serviced` working and will fully approve after that.

**Comment by jbirdkerr** [comment]
Sounds like the easiest path at this point is to build `serviced` locally with your feature branch & get the binary to my CZ. I'm currently installing **zendev2** and will re-attempt the build after that.

**Comment by jbirdkerr** [comment]
For whomever approves this, I see the following in `/opt/serviced/isvcs/resources/logstash/logstash.conf`:

```
output {
    elasticsearch {
        hosts => "elasticsearch:9100"
        template_overwrite => true
    }
    #
        stdout { codec => "json_lines" }


    #
        if [fields][type] == "zenossaudit" {
            file {
              path => "/var/log/serviced/application-audit.log"
              codec => line { format => "%{message}"}
            }
        }
}
```

when the serviced config includes: 
```
SERVICED_LOGSTASH_STDOUT=true
```

**Comment by ealii** [comment]
retest

**Comment by ed-** [comment]
retest this

**Comment by ed-** [comment]
retest this

**Comment by ed-** [comment]
Retest trigger worked, and the tests passed, but it's not reporting results back to here correctly.

**Pull request merged**
