### PR TITLE
fix js linting warnings

### PR DESCRIPTION
**Pull request by wwwtyro**

### CODE REVIEW

**Comment by rDr4g0n** [comment]
test this

**Comment by wwwtyro** [comment]
retest this

**Comment by wwwtyro** [comment]
retest this

**Comment by wwwtyro** [comment]
retest this

**Comment by wwwtyro** [comment]
retest this

**Comment by wwwtyro** [comment]
retest this

**Comment by wwwtyro** [comment]
retest this

**Comment by wwwtyro** [comment]
retest this

**Pull request merged**
