### PR TITLE
CC-1401: Upgrade to Docker 1.9.0

### PR DESCRIPTION
**Pull request by kwalkerz**

### CODE REVIEW

**Comment by kwalkerz** [comment]
retest this

**Comment by kwalkerz** [comment]
This keeps happening:
```----------------------------------------------------------------------
FAIL: controlplanedao_test.go:1101: DaoTest.TestDaoAutoAssignIPs

controlplanedao_test.go:1126:
    t.Fatalf("Error creating host: %v", err)
... Error: Error creating host: fork/exec /usr/bin/hostid: cannot allocate memory
```

And I can see on my dev box that this test takes a little more memory to run with these changes than without.  I will talk to Causey about adding a little more memory to the test slaves.

**Comment by smousa** [comment]
Looks like the build box is out of memory
Probably need to reboot

**Comment by kwalkerz** [comment]
No, it needs more memory added. Mr. Causey is doing that now...

On Wed, Nov 11, 2015 at 1:15 PM, smousa <notifications@github.com> wrote:

> Looks like the build box is out of memory
> Probably need to reboot
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/control-center/serviced/pull/2137#issuecomment-155882796>
> .
>



-- 
*Ken Walker* | Technical Lead
kwalker@zenoss.com | 512.687.6859

<http://www.zenoss.com/>

**Comment by kwalkerz** [comment]
retest this

**Pull request merged**
