### PR TITLE
Use bash when running services as a non-root ruser

### PR DESCRIPTION
**Pull request by jpeacock-zenoss**
When serviced launches a service using a non-root user (given by the RunAs field), explicitly use the bash login shell to execute the Startup command.

Helps fix ZEN-32408.

Using a bash login shell to run services (as user zenoss) provides an environment that most Zenoss applications expect to be running in.

Also fixes zeneventserver's behavior in a zendev environment (it wouldn't start).

### CODE REVIEW

**Comment by StevePC** [comment]
perhaps using /bin/sh -i or /bin/sh --login would be simpler, as that will load the profile and rc files when it executes.

**Comment by jpeacock-zenoss** [comment]
please test this.

**Comment by jpeacock-zenoss** [comment]
please retest this.

**Comment by jpeacock-zenoss** [comment]
please test this.

**Pull request merged**
